/* Mock data for the mail dashboard example */

export type MailFolder = "inbox" | "sent" | "drafts" | "archive" | "spam";

export interface Mail {
  id: string;
  from: string;
  email: string;
  subject: string;
  preview: string;
  body: string[];
  date: string;
  time: string;
  folder: MailFolder;
  starred: boolean;
  unread: boolean;
  attachment?: { name: string; size: string };
}

export const MAILS: Mail[] = [
  {
    id: "m1",
    from: "James Anderson",
    email: "jamesanderson@mail.com",
    subject: "Business Cooperation Agreement",
    preview: "Dear Mr. Richard, I hope this email finds you...",
    body: [
      "Dear Mr. Richard,",
      "I hope this email finds you well.",
      "Please find attached the Business Cooperation Agreement for your review. This contract outlines the terms and conditions discussed during our previous meetings, including the scope of collaboration, responsibilities of both parties, and the proposed timeline.",
      "Kindly review the document and let us know if you have any questions, comments, or require further clarification. We would appreciate receiving your feedback by 13th of January, so we can proceed accordingly.",
      "Thank you for your time and cooperation. We look forward to a successful partnership.",
      "Warm regards,\nJames Anderson",
    ],
    date: "Jan 10",
    time: "10 January 2026, 1:15 PM",
    folder: "inbox",
    starred: true,
    unread: true,
    attachment: { name: "Cooperation Agreement.pdf", size: "2.5 MB" },
  },
  {
    id: "m2",
    from: "Dianne Russell",
    email: "diannerussell@mail.com",
    subject: "Welcome to Flowly!",
    preview: "Hi Richard, Welcome to Flowly! Your account is...",
    body: [
      "Hi Richard,",
      "Welcome to Flowly! Your account is now active and ready to use.",
      "To get started, connect your first workspace and invite your teammates. Our onboarding guide walks you through channels, integrations, and keyboard shortcuts in under ten minutes.",
      "If you have any questions, just reply to this email — a real human reads every message.",
      "Cheers,\nDianne from Flowly",
    ],
    date: "Jan 10",
    time: "10 January 2026, 11:42 AM",
    folder: "inbox",
    starred: false,
    unread: true,
  },
  {
    id: "m3",
    from: "Ralph Edwards",
    email: "ralphedwards@mail.com",
    subject: "Your Flowly trial is ending soon",
    preview: "Hi Richard, Just a heads-up — your Flowly trial...",
    body: [
      "Hi Richard,",
      "Just a heads-up — your Flowly trial ends in three days.",
      "Upgrade now to keep unlimited message history, integrations, and priority support. Teams on the annual plan save 20%.",
      "Questions about plans? Reply here and I'll help you pick the right one.",
      "Best,\nRalph Edwards",
    ],
    date: "Jan 10",
    time: "10 January 2026, 10:05 AM",
    folder: "inbox",
    starred: false,
    unread: true,
  },
  {
    id: "m4",
    from: "Pascal Pedro",
    email: "pascalpedro@mail.com",
    subject: "Get more done in less time",
    preview: "Hi Richard, ready to get more done in less time...",
    body: [
      "Hi Richard,",
      "Ready to get more done in less time?",
      "We just published a productivity playbook covering focus workflows, async communication, and automation recipes used by our fastest-moving customers.",
      "Grab your copy from the resources page — it's free.",
      "Pascal Pedro\nCustomer Success",
    ],
    date: "Jan 10",
    time: "10 January 2026, 9:31 AM",
    folder: "inbox",
    starred: false,
    unread: false,
  },
  {
    id: "m5",
    from: "Giannis Prophen",
    email: "giannisprophen@mail.com",
    subject: "Last chance: 40% off annual plans",
    preview: "Hi Richard, This is your last chance to grab our...",
    body: [
      "Hi Richard,",
      "This is your last chance to grab our biggest discount of the year — 40% off all annual plans.",
      "The offer expires tonight at midnight. After that, prices return to normal.",
      "Upgrade in two clicks from your billing page.",
      "Giannis Prophen\nGrowth Team",
    ],
    date: "Jan 10",
    time: "10 January 2026, 8:12 AM",
    folder: "inbox",
    starred: false,
    unread: false,
  },
  {
    id: "m6",
    from: "Lisa Lauwrens",
    email: "lisalauwrens@mail.com",
    subject: "We just launched something exciting",
    preview: "Hi Richard, We've just launched something exci...",
    body: [
      "Hi Richard,",
      "We've just launched something exciting: real-time collaborative documents, right inside your workspace.",
      "Draft proposals together, leave inline comments, and publish to any channel. No more switching tools mid-thought.",
      "Take the tour from the What's New page.",
      "Lisa Lauwrens\nProduct Team",
    ],
    date: "Jan 10",
    time: "10 January 2026, 7:48 AM",
    folder: "inbox",
    starred: true,
    unread: false,
  },
  {
    id: "m7",
    from: "Clarissa Kim",
    email: "clarissakim@mail.com",
    subject: "It's been a while since your last visit",
    preview: "Hi Richard, It's been a while since your last visit...",
    body: [
      "Hi Richard,",
      "It's been a while since your last visit — your dashboard misses you.",
      "Since you've been away we shipped dark mode, faster search, and a redesigned mobile app.",
      "Log back in to see what's new.",
      "Clarissa Kim\nCommunity Team",
    ],
    date: "Jan 10",
    time: "10 January 2026, 7:02 AM",
    folder: "inbox",
    starred: false,
    unread: false,
  },
  {
    id: "m8",
    from: "Martin Webber",
    email: "martinwebber@mail.com",
    subject: "Big savings just dropped!",
    preview: "Hi Richard, Big savings just dropped! For a limi...",
    body: [
      "Hi Richard,",
      "Big savings just dropped! For a limited time, add unlimited seats to your plan for a flat fee.",
      "Perfect timing if your team is growing this quarter.",
      "See the details on our pricing page.",
      "Martin Webber\nSales",
    ],
    date: "Jan 10",
    time: "10 January 2026, 6:20 AM",
    folder: "inbox",
    starred: false,
    unread: false,
  },
  {
    id: "m9",
    from: "Sarah Thompson",
    email: "sarahthompson@greentech.com",
    subject: "Proposal for business partnership opportunity",
    preview: "Dear Mr. Richard, I hope this message finds you...",
    body: [
      "Dear Mr. Richard,",
      "I hope this message finds you well. I'm Sarah Thompson, Business Development Manager at GreenTech Solutions. We specialize in sustainable energy solutions for residential and commercial properties.",
      "We believe a partnership between our companies could unlock significant value for both sides. I'd love to schedule a 30-minute call next week to explore the opportunity.",
      "Looking forward to hearing from you.",
      "Kind regards,\nSarah Thompson",
    ],
    date: "Jan 5",
    time: "05 January 2026, 1:00 PM",
    folder: "inbox",
    starred: false,
    unread: false,
  },
  {
    id: "m10",
    from: "Anna Roberts",
    email: "annaroberts@mail.com",
    subject: "Re: Q1 marketing budget",
    preview: "Hi Anna, Thanks for the breakdown. The budget...",
    body: [
      "Hi Anna,",
      "Thanks for the breakdown. The budget looks reasonable — approved from my side.",
      "One note: let's shift 10% from paid social to the newsletter sponsorships that performed well last quarter.",
      "Best,\nRichard",
    ],
    date: "Jan 9",
    time: "09 January 2026, 4:20 PM",
    folder: "sent",
    starred: false,
    unread: false,
  },
  {
    id: "m11",
    from: "Legal Team",
    email: "legal@acme.com",
    subject: "Contract redlines for review",
    preview: "Hi team, Attached are my redlines on the vendor...",
    body: [
      "Hi team,",
      "Attached are my redlines on the vendor contract. Main changes: liability cap raised to 12 months of fees, and a 30-day termination clause.",
      "Please review before Friday's call.",
      "Richard",
    ],
    date: "Jan 8",
    time: "08 January 2026, 10:10 AM",
    folder: "sent",
    starred: false,
    unread: false,
    attachment: { name: "Vendor Contract v3.docx", size: "890 KB" },
  },
  {
    id: "m12",
    from: "Draft",
    email: "richardkyle@mail.com",
    subject: "Board update — January (draft)",
    preview: "Team, Here's the January update: revenue is tr...",
    body: [
      "Team,",
      "Here's the January update: revenue is tracking 8% above plan, churn is flat, and the mobile launch slipped one sprint.",
      "TODO: add hiring section before sending.",
    ],
    date: "Jan 7",
    time: "07 January 2026, 9:00 PM",
    folder: "drafts",
    starred: false,
    unread: false,
  },
  {
    id: "m13",
    from: "Github",
    email: "notifications@github.com",
    subject: "[aura-cn] v0.1.0 released",
    preview: "Release v0.1.0 — Initial release is now available...",
    body: [
      "Release v0.1.0 — Initial release is now available.",
      "46 copy-paste React components with rim light, dynamic cursor glow, and micro-interactions.",
      "View the full changelog on GitHub.",
    ],
    date: "Jan 6",
    time: "06 January 2026, 3:33 PM",
    folder: "archive",
    starred: true,
    unread: false,
  },
  {
    id: "m14",
    from: "Crypto Winner",
    email: "no-reply@definitely-legit.biz",
    subject: "You have won 2 BTC!!!",
    preview: "Congratulations!!! Click here immediately to cla...",
    body: [
      "Congratulations!!!",
      "You have been selected to receive 2 BTC. Click the link below immediately to claim your prize before it expires.",
      "This is definitely not a scam.",
    ],
    date: "Jan 4",
    time: "04 January 2026, 2:07 AM",
    folder: "spam",
    starred: false,
    unread: true,
  },
];
